# Speed dating

In [5]:
import pandas as pd

In [9]:
df = pd.read_csv('./data/speeddating.csv')
df.head(7)

,has_null,wave,gender,age,age_o,d_age,d_d_age,race,race_o,samerace,...,d_expected_num_interested_in_me,d_expected_num_matches,like,guess_prob_liked,d_like,d_guess_prob_liked,met,decision,decision_o,match
0,b'',1.0,b'female',21.0,27.0,6.0,b'[4-6]',b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',...,b'[0-3]',b'[3-5]',7.0,6.0,b'[6-8]',b'[5-6]',0.0,b'1',b'0',b'0'
1,b'',1.0,b'female',21.0,22.0,1.0,b'[0-1]',b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',...,b'[0-3]',b'[3-5]',7.0,5.0,b'[6-8]',b'[5-6]',1.0,b'1',b'0',b'0'
2,b'',1.0,b'female',21.0,22.0,1.0,b'[0-1]',b'Asian/Pacific Islander/Asian-American',b'Asian/Pacific Islander/Asian-American',b'1',...,b'[0-3]',b'[3-5]',7.0,NaN,b'[6-8]',b'[0-4]',1.0,b'1',b'1',b'1'
3,b'',1.0,b'female',21.0,23.0,2.0,b'[2-3]',b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',...,b'[0-3]',b'[3-5]',7.0,6.0,b'[6-8]',b'[5-6]',0.0,b'1',b'1',b'1'
4,b'',1.0,b'female',21.0,24.0,3.0,b'[2-3]',b'Asian/Pacific Islander/Asian-American',b'Latino/Hispanic American',b'0',...,b'[0-3]',b'[3-5]',6.0,6.0,b'[6-8]',b'[5-6]',0.0,b'1',b'1',b'1'
5,b'',1.0,b'female',21.0,25.0,4.0,b'[4-6]',b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',...,b'[0-3]',b'[3-5]',6.0,5.0,b'[6-8]',b'[5-6]',0.0,b'0',b'1',b'0'
6,b'',1.0,b'female',21.0,30.0,9.0,b'[7-37]',b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',...,b'[0-3]',b'[3-5]',6.0,5.0,b'[6-8]',b'[5-6]',0.0,b'1',b'0',b'0'

In [10]:
columns_to_drop = ['has_null', 'wave', 'd_d_age', 'd_importance_same_race', 'd_importance_same_religion',
                   'd_pref_o_attractive', 'd_pref_o_sincere', 'd_pref_o_intelligence',
                   'd_pref_o_funny', 'd_pref_o_ambitious', 'd_pref_o_shared_interests',
                   'd_attractive_o', 'd_sinsere_o', 'd_intelligence_o', 'd_funny_o', 'd_ambitous_o', 
                   'd_shared_interests_o', 'd_attractive_important', 'd_sincere_important', 'd_intellicence_important',
                   'attractive_o', 'sinsere_o', 'intelligence_o', 'funny_o', 'ambitous_o', 'shared_interests_o',
                   'd_funny_important', 'd_ambtition_important', 'd_shared_interests_important',
                   'd_attractive', 'd_sincere', 'd_intelligence', 'd_funny', 'd_ambition',
                   'attractive_partner', 'sincere_partner', 'intelligence_partner', 'funny_partner', 'ambition_partner', 'shared_interests_partner', 
                   'd_attractive_partner', 'd_sincere_partner', 'd_intelligence_partner', 'd_funny_partner', 'd_ambition_partner',
                   'd_shared_interests_partner', 'd_sports', 'd_tvsports', 'd_exercise', 'd_dining', 'd_museums',
                   'd_art', 'd_hiking', 'd_gaming', 'd_clubbing', 'd_reading', 'd_tv', 'd_theater', 'd_movies',
                   'd_concerts', 'd_music', 'd_shopping', 'd_yoga', 'd_interests_correlate',
                   'd_expected_happy_with_sd_people', 'd_expected_num_interested_in_me', 'd_expected_num_matches',
                   'd_like', 'd_guess_prob_liked', 'like', 'guess_prob_liked', 'd_like', 'd_guess_prob_liked', 'decision', 'decision_o']

df = df.drop(columns=columns_to_drop)
df.head(7)

,gender,age,age_o,d_age,race,race_o,samerace,importance_same_race,importance_same_religion,field,...,concerts,music,shopping,yoga,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,expected_num_matches,met,match
0,b'female',21.0,27.0,6.0,b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',2.0,4.0,b'Law',...,10.0,9.0,8.0,1.0,0.14,3.0,2.0,4.0,0.0,b'0'
1,b'female',21.0,22.0,1.0,b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',2.0,4.0,b'Law',...,10.0,9.0,8.0,1.0,0.54,3.0,2.0,4.0,1.0,b'0'
2,b'female',21.0,22.0,1.0,b'Asian/Pacific Islander/Asian-American',b'Asian/Pacific Islander/Asian-American',b'1',2.0,4.0,b'Law',...,10.0,9.0,8.0,1.0,0.16,3.0,2.0,4.0,1.0,b'1'
3,b'female',21.0,23.0,2.0,b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',2.0,4.0,b'Law',...,10.0,9.0,8.0,1.0,0.61,3.0,2.0,4.0,0.0,b'1'
4,b'female',21.0,24.0,3.0,b'Asian/Pacific Islander/Asian-American',b'Latino/Hispanic American',b'0',2.0,4.0,b'Law',...,10.0,9.0,8.0,1.0,0.21,3.0,2.0,4.0,0.0,b'1'
5,b'female',21.0,25.0,4.0,b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',2.0,4.0,b'Law',...,10.0,9.0,8.0,1.0,0.25,3.0,2.0,4.0,0.0,b'0'
6,b'female',21.0,30.0,9.0,b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',2.0,4.0,b'Law',...,10.0,9.0,8.0,1.0,0.34,3.0,2.0,4.0,0.0,b'0'

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8378 entries, 0 to 8377
Data columns (total 50 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   gender                         8378 non-null   str
 1   age                            8283 non-null   float64
 2   age_o                          8274 non-null   float64
 3   d_age                          8378 non-null   float64
 4   race                           8378 non-null   str
 5   race_o                         8378 non-null   str
 6   samerace                       8378 non-null   str
 7   importance_same_race           8299 non-null   float64
 8   importance_same_religion       8299 non-null   float64
 9   field                          8378 non-null   str
 10  pref_o_attractive              8289 non-null   float64
 11  pref_o_sincere                 8289 non-null   float64
 12  pref_o_intelligence            8289 non-null   float64
 13  pref_o_funny                   8280 non-null   float64
 14  pref_o_ambitious               8271 non-null   float64
 15  pref_o_shared_interests        8249 non-null   float64
 16  attractive_important           8299 non-null   float64
 17  sincere_important              8299 non-null   float64
 18  intellicence_important         8299 non-null   float64
 19  funny_important                8289 non-null   float64
 20  ambtition_important            8279 non-null   float64
 21  shared_interests_important     8257 non-null   float64
 22  attractive                     8273 non-null   float64
 23  sincere                        8273 non-null   float64
 24  intelligence                   8273 non-null   float64
 25  funny                          8273 non-null   float64
 26  ambition                       8273 non-null   float64
 27  sports                         8299 non-null   float64
 28  tvsports                       8299 non-null   float64
 29  exercise                       8299 non-null   float64
 30  dining                         8299 non-null   float64
 31  museums                        8299 non-null   float64
 32  art                            8299 non-null   float64
 33  hiking                         8299 non-null   float64
 34  gaming                         8299 non-null   float64
 35  clubbing                       8299 non-null   float64
 36  reading                        8299 non-null   float64
 37  tv                             8299 non-null   float64
 38  theater                        8299 non-null   float64
 39  movies                         8299 non-null   float64
 40  concerts                       8299 non-null   float64
 41  music                          8299 non-null   float64
 42  shopping                       8299 non-null   float64
 43  yoga                           8299 non-null   float64
 44  interests_correlate            8220 non-null   float64
 45  expected_happy_with_sd_people  8277 non-null   float64
 46  expected_num_interested_in_me  1800 non-null   float64
 47  expected_num_matches           7205 non-null   float64
 48  met                            8003 non-null   float64
 49  match                          8378 non-null   str
dtypes: float64(44), str(6)
memory usage: 3.2 MB

In [11]:
print("liczba duplikatów:")
print(df.duplicated().sum())
df[df.duplicated(keep=False)]

liczba duplikatów:
10

,gender,age,age_o,d_age,race,race_o,samerace,importance_same_race,importance_same_religion,field,...,concerts,music,shopping,yoga,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,expected_num_matches,met,match
910,b'male',29.0,NaN,29.0,b'Latino/Hispanic American',b'?',b'0',1.0,1.0,b'Business & International Affairs',...,4.0,6.0,4.0,2.0,NaN,5.0,3.0,3.0,NaN,b'0'
911,b'male',29.0,NaN,29.0,b'Latino/Hispanic American',b'?',b'0',1.0,1.0,b'Business & International Affairs',...,4.0,6.0,4.0,2.0,NaN,5.0,3.0,3.0,NaN,b'0'
920,b'male',22.0,NaN,22.0,b'Other',b'?',b'0',1.0,1.0,b'Law',...,9.0,9.0,2.0,1.0,NaN,5.0,1.0,3.0,NaN,b'0'
921,b'male',22.0,NaN,22.0,b'Other',b'?',b'0',1.0,1.0,b'Law',...,9.0,9.0,2.0,1.0,NaN,5.0,1.0,3.0,NaN,b'0'
930,b'male',27.0,NaN,27.0,b'Black/African American',b'?',b'0',1.0,1.0,b'MFA Creative Writing',...,7.0,7.0,7.0,1.0,NaN,5.0,2.0,NaN,0.0,b'0'
931,b'male',27.0,NaN,27.0,b'Black/African American',b'?',b'0',1.0,1.0,b'MFA Creative Writing',...,7.0,7.0,7.0,1.0,NaN,5.0,2.0,NaN,0.0,b'0'
940,b'male',28.0,NaN,28.0,b'European/Caucasian-American',b'?',b'0',2.0,2.0,b'MBA',...,6.0,7.0,2.0,1.0,NaN,3.0,0.0,1.0,0.0,b'0'
941,b'male',28.0,NaN,28.0,b'European/Caucasian-American',b'?',b'0',2.0,2.0,b'MBA',...,6.0,7.0,2.0,1.0,NaN,3.0,0.0,1.0,0.0,b'0'
970,b'male',22.0,NaN,22.0,b'European/Caucasian-American',b'?',b'0',8.0,1.0,b'Engineering',...,6.0,8.0,8.0,4.0,NaN,7.0,9.0,1.0,0.0,b'0'
971,b'male',22.0,NaN,22.0,b'European/Caucasian-American',b'?',b'0',8.0,1.0,b'Engineering',...,6.0,8.0,8.0,4.0,NaN,7.0,9.0,1.0,0.0,b'0'
4887,b'female',36.0,NaN,36.0,b'Black/African American',b'?',b'0',5.0,5.0,b'Instructional Media and Technology',...,10.0,10.0,10.0,8.0,NaN,8.0,NaN,5.0,0.0,b'0'
4888,b'female',36.0,NaN,36.0,b'Black/African American',b'?',b'0',5.0,5.0,b'Instructional Media and Technology',...,10.0,10.0,10.0,8.0,NaN,8.0,NaN,5.0,0.0,b'0'
4896,b'female',29.0,NaN,29.0,b'European/Caucasian-American',b'?',b'0',2.0,7.0,b'SIPA / MIA',...,9.0,9.0,1.0,5.0,NaN,5.0,NaN,0.0,0.0,b'0'
4897,b'female',29.0,NaN,29.0,b'European/Caucasian-American',b'?',b'0',2.0,7.0,b'SIPA / MIA',...,9.0,9.0,1.0,5.0,NaN,5.0,NaN,0.0,0.0,b'0'
4914,b'female',29.0,NaN,29.0,b'European/Caucasian-American',b'?',b'0',1.0,1.0,b'art education',...,6.0,8.0,2.0,1.0,NaN,4.0,NaN,1.0,0.0,b'0'
4915,b'female',29.0,NaN,29.0,b'European/Caucasian-American',b'?',b'0',1.0,1.0,b'art education',...,6.0,8.0,2.0,1.0,NaN,4.0,NaN,1.0,0.0,b'0'
4923,b'female',22.0,NaN,22.0,b'Asian/Pacific Islander/Asian-American',b'?',b'0',3.0,3.0,b'MA in Quantitative Methods',...,4.0,9.0,5.0,2.0,NaN,7.0,NaN,2.0,0.0,b'0'
4924,b'female',22.0,NaN,22.0,b'Asian/Pacific Islander/Asian-American',b'?',b'0',3.0,3.0,b'MA in Quantitative Methods',...,4.0,9.0,5.0,2.0,NaN,7.0,NaN,2.0,0.0,b'0'
4932,b'female',34.0,NaN,34.0,b'European/Caucasian-American',b'?',b'0',1.0,1.0,b'Early Childhood Education',...,9.0,9.0,4.0,10.0,NaN,4.0,NaN,2.0,0.0,b'0'
4933,b'female',34.0,NaN,34.0,b'European/Caucasian-American',b'?',b'0',1.0,1.0,b'Early Childhood Education',...,9.0,9.0,4.0,10.0,NaN,4.0,NaN,2.0,0.0,b'0'

In [13]:
df = df.drop_duplicates()
df.info()

<class 'pandas.DataFrame'>
Index: 8368 entries, 0 to 8377
Data columns (total 50 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   gender                         8368 non-null   str
 1   age                            8273 non-null   float64
 2   age_o                          8274 non-null   float64
 3   d_age                          8368 non-null   float64
 4   race                           8368 non-null   str
 5   race_o                         8368 non-null   str
 6   samerace                       8368 non-null   str
 7   importance_same_race           8289 non-null   float64
 8   importance_same_religion       8289 non-null   float64
 9   field                          8368 non-null   str
 10  pref_o_attractive              8289 non-null   float64
 11  pref_o_sincere                 8289 non-null   float64
 12  pref_o_intelligence            8289 non-null   float64
 13  pref_o_funny                   8280 non-null   float64
 14  pref_o_ambitious               8271 non-null   float64
 15  pref_o_shared_interests        8249 non-null   float64
 16  attractive_important           8289 non-null   float64
 17  sincere_important              8289 non-null   float64
 18  intellicence_important         8289 non-null   float64
 19  funny_important                8279 non-null   float64
 20  ambtition_important            8269 non-null   float64
 21  shared_interests_important     8247 non-null   float64
 22  attractive                     8263 non-null   float64
 23  sincere                        8263 non-null   float64
 24  intelligence                   8263 non-null   float64
 25  funny                          8263 non-null   float64
 26  ambition                       8263 non-null   float64
 27  sports                         8289 non-null   float64
 28  tvsports                       8289 non-null   float64
 29  exercise                       8289 non-null   float64
 30  dining                         8289 non-null   float64
 31  museums                        8289 non-null   float64
 32  art                            8289 non-null   float64
 33  hiking                         8289 non-null   float64
 34  gaming                         8289 non-null   float64
 35  clubbing                       8289 non-null   float64
 36  reading                        8289 non-null   float64
 37  tv                             8289 non-null   float64
 38  theater                        8289 non-null   float64
 39  movies                         8289 non-null   float64
 40  concerts                       8289 non-null   float64
 41  music                          8289 non-null   float64
 42  shopping                       8289 non-null   float64
 43  yoga                           8289 non-null   float64
 44  interests_correlate            8220 non-null   float64
 45  expected_happy_with_sd_people  8267 non-null   float64
 46  expected_num_interested_in_me  1795 non-null   float64
 47  expected_num_matches           7196 non-null   float64
 48  met                            7995 non-null   float64
 49  match                          8368 non-null   str
dtypes: float64(44), str(6)
memory usage: 3.3 MB